#!/usr/bin/env bash

file_path=$1
server_ip=$2
username=$3
private_key_path=$4

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2"
