#!/usr/bin/env bash

#installing Nginx on web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo echo "Hello, World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
