#!/usr/bin/env bash
#installing Nginx on web server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/
echo "Hello, World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
