#!/usr/bin/env bash

#installing Nginx on web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo "Hello, World!" | sudo tee /var/www/html/index.html
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name_;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~redirect_me) {
		rewrite ^https://www.youtube.com/ permanent;
	}
}"

bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)"-le 0 ];
then
	service nginx start
else
	service nginx restart
fi
