#!/usr/bin/env bash
#installing Nginx on web server

sudo apt-get update
sudo apt-get install nginx -y

if [ -x /usr/sbin/nginx ]; then
	sudo rm /etc/nginx/sites-available/default
	sudo rm /etc/nginx/sites-enabled/default

	sudo touch /etc/nginx/sites-available/default
	echo "server {
	    listen 80;
	    root /var/www/html;
	    index index.html;

	    location / redirect_me {
	    	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	    }

	    location / {
	    	try_files \$uri \$uri/ =404;
	    }
    	}" | sudo tee /etc/nginx/sites-available/default
	
	sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

	sudo nginx -t
	sudo service nginx reload
else
	echo "nginx installation failed."
fi
