#!/usr/bin/env bash
#installing Nginx on web server

sudo apt-get update && sudo apt-get upgrade -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i '/server_name_;/a \
    error_page 404 /404.html;\n\
    location = /404.html {\n\
    	internal;\n\
    }' /etc/nginx/sites-available/default
sudo service nginx restart
