#!/usr/bin/env bash
# install nginx and customize header
sudo apt-get update
sudo apt-get -y install nginx
custom_header="add_header X-Served-By \$hostname;"
sudo echo "$custom_header" | sudo tee -a /etc/nginx/sites-available/default > /dev/null
sudo service nginx restart
