#!/usr/bin/env bash
#install and conffigure HAproxy on lb-01 server
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get install haproxy

#configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 255488-web-01 52.205.85.168 check
    server 255488-web-02 52.91.157.43:80 check
"
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy start
