#!/usr/bin/env bash

#This script displays "Best school" times
#After the 9th iteration display "Hi"

count=0

while [ $count -lt 10 ]

do 
	echo "Best School"
	if [ $count -eq 8 ]
	then
		echo "Hi"
	fi
	((count++))
done
