#!/usr/bin/env bash

#displays information about the "school" file

file="school"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ -s "$file" ]
	then
		echo "school file is not empty"
		if [ -f "$file" ]
		then
			echo "school is a regular file"
		else
			:
		fi
	else
		echo "school file is empty"
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
