#!/usr/bin/env bash
#run nginx as nginx
sed -i "s/#user www-data/user ubuntu/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
service apache2 stop
service nginx restart
