#!/usr/bin/env bash
#run nginx as nginx
sudo systemctl stop nginx
sudo sed -i "s/#user www-data/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
service apache2 stop
service nginx restart
